# SPDX-FileCopyrightText: 2026 ReallyMe LLC

# SPDX-License-Identifier: MIT OR Apache-2.0

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Copenhagen
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
